name: Publish Helm Charts

on:
  repository_dispatch:
    types: [publish-helm-charts]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.10.0

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Checkout Application Repository
        uses: actions/checkout@v3
        with:
          repository: PranayV66/flask-kubernetes-app
            #path: flask-kubernetes-app
          path: /
          token: ${{ secrets.GH_PAT }}

      - name: Move helm charts to helm-repo directory
        run: |
          mkdir -p helm-repo
          pwd
          ls -ltr /
          ls -ltr /flask-kubernetes-app/charts
          #cp flask-kubernetes-app/charts/flask-kubernetes-app/*.tgz helm-repo/
          cp /flask-kubernetes-app/charts/*.tgz helm-repo/

      - name: Generate or update index.html
        run: |
          helm repo index helm-repo/ --url https://github.com/PranayV66/flask-kubernetes-app-helm

      - name: Commit and push helm charts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add helm-repo/ index.yaml
          git commit -m "Publish new Helm charts" || echo "No changes to commit"
          git puh origin gh-pages
